# Generated by Django 4.0.8 on 2026-02-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['plan_tier', 'is_active'], name='profile_plan_active_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'status'], name='project_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'updated_at'], name='project_owner_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.CheckConstraint(check=models.Q(('plan_tier__in', ('free', 'pro', 'enterprise'))), name='profile_plan_tier_valid'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='project_owner_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('monthly_recurring_revenue__gte', 0)), name='project_mrr_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='project_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(check=models.Q(('slug', ''), _negated=True), name='project_slug_not_empty'),
        ),
    ]
