# Generated by Django 4.0.8 on 2026-02-16 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requested', max_length=24)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('meeting_url', models.URLField(blank=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_customer_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=180)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='DigitalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file_path', models.CharField(max_length=420)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('version_label', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DownloadGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_downloads', models.PositiveIntegerField(default=5)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(db_index=True, max_length=80)),
                ('source_type', models.CharField(choices=[('plan', 'Plan'), ('purchase', 'Purchase'), ('manual', 'Manual')], default='purchase', max_length=24)),
                ('source_reference', models.CharField(blank=True, max_length=128)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], default='pending_payment', max_length=24)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('tax_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('clerk_checkout_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_amount_cents', models.PositiveIntegerField(default=0)),
                ('total_amount_cents', models.PositiveIntegerField(default=0)),
                ('product_name_snapshot', models.CharField(blank=True, max_length=180)),
                ('price_name_snapshot', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('clerk', 'Clerk'), ('manual', 'Manual')], default='clerk', max_length=24)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=24)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('billing_period', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='one_time', max_length=20)),
                ('clerk_plan_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('clerk_price_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('amount_cents', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('digital', 'Digital'), ('service', 'Service')], default='digital', max_length=24)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('feature_keys', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_minutes', models.PositiveIntegerField(default=60)),
                ('delivery_days', models.PositiveIntegerField(default=7)),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('onboarding_instructions', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('paused', 'Paused')], default='incomplete', max_length=20)),
                ('clerk_subscription_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('clerk', 'Clerk'), ('stripe', 'Stripe'), ('other', 'Other')], default='clerk', max_length=24)),
                ('event_id', models.CharField(max_length=191)),
                ('event_type', models.CharField(max_length=191)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', max_length=24)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['status', 'received_at'], name='webhook_status_received_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='webhook_provider_event_unique'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.customeraccount'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.price'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.product'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_offer', to='api.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='active_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_products', to='api.price'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_products', to='api.profile'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.product'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.order'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.subscription'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.price'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.customeraccount'),
        ),
        migrations.AddField(
            model_name='entitlement',
            name='customer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='api.customeraccount'),
        ),
        migrations.AddField(
            model_name='downloadgrant',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_grants', to='api.digitalasset'),
        ),
        migrations.AddField(
            model_name='downloadgrant',
            name='customer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_grants', to='api.customeraccount'),
        ),
        migrations.AddField(
            model_name='downloadgrant',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_grants', to='api.orderitem'),
        ),
        migrations.AddField(
            model_name='digitalasset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.product'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to='api.profile'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.customeraccount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.orderitem'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.serviceoffer'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer_account', 'status'], name='sub_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['owner', 'visibility'], name='product_owner_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'visibility'], name='product_type_visibility_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='product_owner_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='product_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('slug', ''), _negated=True), name='product_slug_not_empty'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product', 'is_active'], name='price_product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['billing_period', 'is_active'], name='price_period_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='price_one_default_per_product'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'external_id'], name='txn_provider_external_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'updated_at'], name='txn_status_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(check=models.Q(('order__isnull', False), ('subscription__isnull', False), _connector='OR'), name='txn_order_or_sub_required'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='order_item_order_product_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_account', 'status'], name='order_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'updated_at'], name='order_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['customer_account', 'is_active'], name='entitlement_cust_active_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlement',
            index=models.Index(fields=['feature_key', 'is_active'], name='entitlement_feature_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.UniqueConstraint(fields=('customer_account', 'feature_key', 'source_type', 'source_reference'), name='entitlement_source_unique'),
        ),
        migrations.AddIndex(
            model_name='downloadgrant',
            index=models.Index(fields=['customer_account', 'is_active'], name='grant_customer_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='downloadgrant',
            constraint=models.UniqueConstraint(fields=('order_item', 'asset'), name='grant_order_item_asset_unique'),
        ),
        migrations.AddIndex(
            model_name='digitalasset',
            index=models.Index(fields=['product', 'is_active'], name='asset_product_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='digitalasset',
            constraint=models.UniqueConstraint(fields=('product', 'file_path'), name='asset_product_path_unique'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer_account', 'status'], name='booking_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['scheduled_start'], name='booking_scheduled_start_idx'),
        ),
    ]
