from django.urls import path

from .views import (
    AiProviderListView,
    AiUsageSummaryView,
    AccountBookingListCreateView,
    AccountCustomerView,
    AccountDownloadAccessView,
    AccountDownloadGrantListView,
    AccountEntitlementListView,
    AccountOrderConfirmView,
    AccountOrderCreateView,
    AccountOrderListView,
    AccountSubscriptionListView,
    BillingFeatureView,
    ClerkUserView,
    HealthView,
    MeView,
    ProfileView,
    ProjectDetailView,
    ProjectListCreateView,
    PublicProductDetailView,
    PublicProductListView,
    SellerAssetDetailView,
    SellerAssetListCreateView,
    SellerPriceDetailView,
    SellerPriceListCreateView,
    SellerProductDetailView,
    SellerProductListCreateView,
    SellerServiceOfferView,
    SupabaseProfileView,
)
from .webhooks import ClerkWebhookView

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("me/", MeView.as_view(), name="me"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("me/clerk/", ClerkUserView.as_view(), name="clerk-user"),
    path("billing/features/", BillingFeatureView.as_view(), name="billing-features"),
    path("ai/providers/", AiProviderListView.as_view(), name="ai-provider-list"),
    path("ai/usage/summary/", AiUsageSummaryView.as_view(), name="ai-usage-summary"),
    path("projects/", ProjectListCreateView.as_view(), name="project-list"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("products/", PublicProductListView.as_view(), name="product-public-list"),
    path("products/<slug:slug>/", PublicProductDetailView.as_view(), name="product-public-detail"),
    path("account/customer/", AccountCustomerView.as_view(), name="account-customer"),
    path("account/orders/", AccountOrderListView.as_view(), name="account-order-list"),
    path("account/orders/create/", AccountOrderCreateView.as_view(), name="account-order-create"),
    path(
        "account/orders/<uuid:public_id>/confirm/",
        AccountOrderConfirmView.as_view(),
        name="account-order-confirm",
    ),
    path("account/subscriptions/", AccountSubscriptionListView.as_view(), name="account-subscription-list"),
    path("account/entitlements/", AccountEntitlementListView.as_view(), name="account-entitlement-list"),
    path("account/downloads/", AccountDownloadGrantListView.as_view(), name="account-download-list"),
    path(
        "account/downloads/<uuid:token>/access/",
        AccountDownloadAccessView.as_view(),
        name="account-download-access",
    ),
    path("account/bookings/", AccountBookingListCreateView.as_view(), name="account-booking-list-create"),
    path("seller/products/", SellerProductListCreateView.as_view(), name="seller-product-list-create"),
    path("seller/products/<int:pk>/", SellerProductDetailView.as_view(), name="seller-product-detail"),
    path(
        "seller/products/<int:product_id>/prices/",
        SellerPriceListCreateView.as_view(),
        name="seller-price-list-create",
    ),
    path("seller/prices/<int:pk>/", SellerPriceDetailView.as_view(), name="seller-price-detail"),
    path(
        "seller/products/<int:product_id>/assets/",
        SellerAssetListCreateView.as_view(),
        name="seller-asset-list-create",
    ),
    path("seller/assets/<int:pk>/", SellerAssetDetailView.as_view(), name="seller-asset-detail"),
    path(
        "seller/products/<int:product_id>/service-offer/",
        SellerServiceOfferView.as_view(),
        name="seller-service-offer",
    ),
    path("supabase/profile/", SupabaseProfileView.as_view(), name="supabase-profile"),
    path("webhooks/clerk/", ClerkWebhookView.as_view(), name="clerk-webhook"),
]
